name: Sync Leetcode

on:
  workflow_dispatch:      # (중요) 우리가 버튼을 눌러서 직접 실행할 수 있게 해줍니다.
  schedule:
    - cron: "0 4 * * *"  # 매일 한국 시간 오전 9시에 자동으로 돌아갑니다.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync
        uses: joshcai/leetcode-sync@v1.7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          destination-folder: 'my-solutions' # 깃허브에 저장될 폴더 이름입니다.
